const wageData = [
    {
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},
{
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},
{
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},
{
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},
{
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},
{
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},
{
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},
{
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},
{
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},
{
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},
{
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},
{
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},
{
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},
{
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},
{
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},
{
    name: "AMBIKESH MISHRA",
    empid: "ACTION-SE-001/010",
    des: "SECURITY GUARD",
    day: 0,
    unit: "",
    daily: "",
    basic: 0,
    hra: 0,
    site: 0,
    other: "",
    total: 0,
    esi: 0,
    pf: 0,
    pt: 0,
    td: 0,
    net: 0,
    sign: "",
    initial: ""
},


]

module.exports = wageData;
